import type { SVGDiagramData } from "./SVGDiagram";

export const DIAGRAM_DATA: Record<string, SVGDiagramData> = {
  "agent-orchestration": {
    nodes: [
      { id: "oracle", label: { ko: "심판관 (Oracle)", en: "Oracle" }, x: 280, y: 0, delay: 0, tooltip: { ko: "최종 기획 결정 및 아키텍처 승인", en: "Final planning decisions & architecture approval" } },
      { id: "architect", label: { ko: "기반설계자 (Architect)", en: "Architect" }, x: 0, y: 100, delay: 0.05, tooltip: { ko: "k3s 인프라, CI/CD 파이프라인 설계", en: "k3s infra, CI/CD pipeline design" } },
      { id: "conductor", label: { ko: "지휘자 (Conductor)", en: "Conductor" }, x: 210, y: 100, delay: 0.1, tooltip: { ko: "배포 파이프라인 오케스트레이션", en: "Deployment pipeline orchestration" } },
      { id: "gatekeeper", label: { ko: "관문지기 (Gatekeeper)", en: "Gatekeeper" }, x: 420, y: 100, delay: 0.15, tooltip: { ko: "인증/보안 — OAuth, JWT, Rate Limit", en: "Auth/Security — OAuth, JWT, Rate Limit" } },
      { id: "postman", label: { ko: "배달부 (Postman)", en: "Postman" }, x: 0, y: 210, delay: 0.2, tooltip: { ko: "API 설계 및 서비스 간 통신", en: "API design & inter-service communication" } },
      { id: "curator", label: { ko: "출제자 (Curator)", en: "Curator" }, x: 210, y: 210, delay: 0.25, tooltip: { ko: "문제 도메인 CRUD 및 주차별 관리", en: "Problem domain CRUD & weekly management" } },
      { id: "scribe", label: { ko: "서기관 (Scribe)", en: "Scribe" }, x: 420, y: 210, delay: 0.3, tooltip: { ko: "Saga 오케스트레이션 및 트랜잭션 관리", en: "Saga orchestration & transaction management" } },
      { id: "palette", label: { ko: "화가 (Palette)", en: "Palette" }, x: 630, y: 210, delay: 0.35, tooltip: { ko: "UI/UX 구현 — Next.js, shadcn/ui", en: "UI/UX implementation — Next.js, shadcn/ui" } },
      { id: "sensei", label: { ko: "분석가 (Sensei)", en: "Sensei" }, x: 0, y: 320, delay: 0.4, tooltip: { ko: "AI 파이프라인 — Claude API, Circuit Breaker", en: "AI pipeline — Claude API, Circuit Breaker" } },
      { id: "herald", label: { ko: "전령 (Herald)", en: "Herald" }, x: 210, y: 320, delay: 0.45, tooltip: { ko: "SSE 실시간 알림 및 상태 브로드캐스트", en: "SSE real-time alerts & state broadcast" } },
      { id: "scout", label: { ko: "정찰병 (Scout)", en: "Scout" }, x: 420, y: 320, delay: 0.5, tooltip: { ko: "GitHub 연동 — Octokit Push, 멱등성 처리", en: "GitHub integration — Octokit Push, idempotency" } },
      { id: "librarian", label: { ko: "기록관리자 (Librarian)", en: "Librarian" }, x: 630, y: 320, delay: 0.55, tooltip: { ko: "ADR 문서화 및 런북 관리", en: "ADR docs & runbook management" } },
    ],
    edges: [
      { id: "e-oracle-architect", source: "oracle", target: "architect" },
      { id: "e-oracle-conductor", source: "oracle", target: "conductor" },
      { id: "e-oracle-gatekeeper", source: "oracle", target: "gatekeeper" },
      { id: "e-oracle-palette", source: "oracle", target: "palette" },
      { id: "e-architect-postman", source: "architect", target: "postman" },
      { id: "e-conductor-curator", source: "conductor", target: "curator" },
      { id: "e-gatekeeper-scribe", source: "gatekeeper", target: "scribe" },
      { id: "e-postman-sensei", source: "postman", target: "sensei" },
      { id: "e-curator-scout", source: "curator", target: "scout" },
      { id: "e-scribe-herald", source: "scribe", target: "herald" },
      { id: "e-palette-librarian", source: "palette", target: "librarian" },
    ],
  },

  overall: {
    nodes: [
      { id: "client", label: { ko: "Next.js Client", en: "Next.js Client" }, x: 0, y: 120, delay: 0, tooltip: { ko: "SSR + CSR 하이브리드 렌더링", en: "SSR + CSR hybrid rendering" } },
      { id: "gateway", label: { ko: "API Gateway", en: "API Gateway" }, x: 200, y: 120, delay: 0.1, tooltip: { ko: "NestJS — 인증, Rate Limit, 프록시", en: "NestJS — Auth, Rate Limit, Proxy" } },
      { id: "identity", label: { ko: "Identity Service", en: "Identity Service" }, x: 420, y: 30, delay: 0.2, tooltip: { ko: "OAuth 2.0 + JWT 토큰 관리", en: "OAuth 2.0 + JWT token management" } },
      { id: "submission", label: { ko: "Submission Service", en: "Submission Service" }, x: 420, y: 120, delay: 0.2, tooltip: { ko: "코드 제출 + Saga 오케스트레이션", en: "Code submission + Saga orchestration" } },
      { id: "problem", label: { ko: "Problem Service", en: "Problem Service" }, x: 420, y: 210, delay: 0.2, tooltip: { ko: "문제 CRUD + 주차별 관리", en: "Problem CRUD + weekly management" } },
      { id: "rabbitmq", label: { ko: "RabbitMQ 3.13", en: "RabbitMQ 3.13" }, x: 640, y: 165, delay: 0.3, tooltip: { ko: "비동기 메시지 큐 — Task Queue 패턴", en: "Async message queue — Task Queue pattern" } },
      { id: "gh-worker", label: { ko: "GitHub Worker", en: "GitHub Worker" }, x: 640, y: 30, delay: 0.4, tooltip: { ko: "Octokit — 코드 Push + 멱등성 처리", en: "Octokit — code Push + idempotency" } },
      { id: "ai-worker", label: { ko: "AI Analysis (FastAPI)", en: "AI Analysis (FastAPI)" }, x: 640, y: 280, delay: 0.4, tooltip: { ko: "Claude API + Circuit Breaker", en: "Claude API + Circuit Breaker" } },
      { id: "postgres", label: { ko: "PostgreSQL 16", en: "PostgreSQL 16" }, x: 420, y: 330, delay: 0.5, tooltip: { ko: "메인 DB — 서비스별 스키마 분리", en: "Main DB — per-service schema isolation" } },
      { id: "redis", label: { ko: "Redis 7.2", en: "Redis 7.2" }, x: 200, y: 270, delay: 0.5, tooltip: { ko: "세션 캐시 + Rate Limit 카운터", en: "Session cache + Rate Limit counters" } },
    ],
    edges: [
      { id: "e-c-g", source: "client", target: "gateway" },
      { id: "e-g-i", source: "gateway", target: "identity" },
      { id: "e-g-s", source: "gateway", target: "submission" },
      { id: "e-g-p", source: "gateway", target: "problem" },
      { id: "e-s-rmq", source: "submission", target: "rabbitmq" },
      { id: "e-rmq-gh", source: "rabbitmq", target: "gh-worker" },
      { id: "e-rmq-ai", source: "rabbitmq", target: "ai-worker" },
      { id: "e-s-db", source: "submission", target: "postgres", dashed: true },
      { id: "e-g-redis", source: "gateway", target: "redis", dashed: true },
    ],
  },

  "api-gateway": {
    nodes: [
      { id: "client", label: { ko: "Client Request", en: "Client Request" }, x: 0, y: 80, delay: 0, tooltip: { ko: "브라우저 HTTP 요청", en: "Browser HTTP request" } },
      { id: "req-id", label: { ko: "RequestId MW", en: "RequestId MW" }, x: 200, y: 80, delay: 0.08, tooltip: { ko: "요청 추적용 고유 ID 부여", en: "Unique ID for request tracing" } },
      { id: "security", label: { ko: "Security Headers", en: "Security Headers" }, x: 400, y: 80, delay: 0.16, tooltip: { ko: "CORS, CSP, XSS 보호 헤더", en: "CORS, CSP, XSS protection headers" } },
      { id: "rate-limit", label: { ko: "Rate Limit", en: "Rate Limit" }, x: 200, y: 180, delay: 0.24, tooltip: { ko: "IP별 분당 요청 제한 (Redis)", en: "Per-IP rate limiting (Redis)" } },
      { id: "jwt", label: { ko: "JWT Auth", en: "JWT Auth" }, x: 400, y: 180, delay: 0.32, tooltip: { ko: "Access Token 검증 + Role 확인", en: "Access Token validation + Role check" } },
      { id: "proxy", label: { ko: "Proxy Dispatch", en: "Proxy Dispatch" }, x: 600, y: 130, delay: 0.4, tooltip: { ko: "화이트리스트 기반 서비스 라우팅", en: "Whitelist-based service routing" } },
      { id: "services", label: { ko: "Microservices", en: "Microservices" }, x: 600, y: 230, delay: 0.48, tooltip: { ko: "5개 타겟 서비스로 프록시", en: "Proxy to 5 target services" } },
      { id: "redis", label: { ko: "Redis (Quota)", en: "Redis (Quota)" }, x: 0, y: 180, delay: 0.24, tooltip: { ko: "Rate Limit 카운터 + 상태 저장", en: "Rate Limit counters + state storage" } },
    ],
    edges: [
      { id: "e1", source: "client", target: "req-id" },
      { id: "e2", source: "req-id", target: "security" },
      { id: "e3", source: "security", target: "rate-limit" },
      { id: "e4", source: "rate-limit", target: "jwt" },
      { id: "e5", source: "jwt", target: "proxy" },
      { id: "e6", source: "proxy", target: "services" },
      { id: "e-rl-redis", source: "rate-limit", target: "redis", dashed: true },
    ],
  },

  "ai-pipeline": {
    nodes: [
      { id: "frontend", label: { ko: "Frontend (Monaco)", en: "Frontend (Monaco)" }, x: 0, y: 80, delay: 0, tooltip: { ko: "Monaco Editor — 코드 입력 UI", en: "Monaco Editor — code input UI" } },
      { id: "gateway", label: { ko: "Gateway", en: "Gateway" }, x: 200, y: 80, delay: 0.1, tooltip: { ko: "인증 + 일일 제출 횟수 검증", en: "Auth + daily submission limit check" } },
      { id: "submission", label: { ko: "Submission Svc", en: "Submission Svc" }, x: 400, y: 80, delay: 0.2, tooltip: { ko: "DB 저장 + Saga 시작", en: "DB save + Saga start" } },
      { id: "rabbitmq", label: { ko: "RabbitMQ", en: "RabbitMQ" }, x: 400, y: 190, delay: 0.3, tooltip: { ko: "GitHub/AI 작업 큐 발행", en: "GitHub/AI job queue dispatch" } },
      { id: "gh-worker", label: { ko: "GitHub Worker", en: "GitHub Worker" }, x: 600, y: 20, delay: 0.4, tooltip: { ko: "코드 Push + PR 자동 생성", en: "Code Push + auto PR creation" } },
      { id: "ai-worker", label: { ko: "AI Analysis", en: "AI Analysis" }, x: 600, y: 140, delay: 0.4, tooltip: { ko: "Claude API 호출 + 분석 실행", en: "Claude API call + analysis execution" } },
      { id: "claude", label: { ko: "Claude Haiku", en: "Claude Haiku" }, x: 600, y: 260, delay: 0.5, tooltip: { ko: "코드 리뷰 + 개선점 생성", en: "Code review + improvement suggestions" } },
      { id: "sse", label: { ko: "SSE Stream", en: "SSE Stream" }, x: 200, y: -40, delay: 0.6, tooltip: { ko: "실시간 분석 진행 상태 스트리밍", en: "Real-time analysis progress streaming" } },
      { id: "redis-quota", label: { ko: "Redis Quota (5/day)", en: "Redis Quota (5/day)" }, x: 200, y: 190, delay: 0.3, tooltip: { ko: "사용자별 일일 5회 제한", en: "Per-user daily limit (5/day)" } },
    ],
    edges: [
      { id: "e1", source: "frontend", target: "gateway" },
      { id: "e2", source: "gateway", target: "submission" },
      { id: "e3", source: "submission", target: "rabbitmq" },
      { id: "e4", source: "rabbitmq", target: "gh-worker" },
      { id: "e5", source: "rabbitmq", target: "ai-worker" },
      { id: "e6", source: "ai-worker", target: "claude" },
      { id: "e7", source: "ai-worker", target: "sse" },
      { id: "e8", source: "sse", target: "frontend" },
      { id: "e-sub-redis", source: "submission", target: "redis-quota", dashed: true },
    ],
  },

  saga: {
    nodes: [
      { id: "db-saved", label: { ko: "DB_SAVED (Start)", en: "DB_SAVED (Start)" }, x: 0, y: 80, delay: 0, tooltip: { ko: "제출 데이터 DB 저장 완료", en: "Submission data saved to DB" } },
      { id: "gh-queued", label: { ko: "GITHUB_QUEUED", en: "GITHUB_QUEUED" }, x: 220, y: 80, delay: 0.1, tooltip: { ko: "GitHub Push 큐 발행 (5분 타임아웃)", en: "GitHub Push queued (5min timeout)" } },
      { id: "ai-queued", label: { ko: "AI_QUEUED", en: "AI_QUEUED" }, x: 440, y: 80, delay: 0.2, tooltip: { ko: "AI 분석 큐 발행 (30분 타임아웃)", en: "AI analysis queued (30min timeout)" } },
      { id: "done", label: { ko: "DONE", en: "DONE" }, x: 660, y: 80, delay: 0.3, tooltip: { ko: "전체 파이프라인 완료", en: "Full pipeline completed" } },
      { id: "token-invalid", label: { ko: "TOKEN_INVALID", en: "TOKEN_INVALID" }, x: 220, y: 210, delay: 0.4, tooltip: { ko: "GitHub 토큰 만료 → 보상 트랜잭션", en: "GitHub token expired → compensating tx" } },
      { id: "ai-skipped", label: { ko: "AI_SKIPPED", en: "AI_SKIPPED" }, x: 440, y: 210, delay: 0.4, tooltip: { ko: "AI 분석 스킵 (할당량 초과)", en: "AI analysis skipped (quota exceeded)" } },
      { id: "delayed", label: { ko: "DELAYED", en: "DELAYED" }, x: 660, y: 210, delay: 0.4, tooltip: { ko: "일시 지연 → 재시도 대기", en: "Temporarily delayed → retry pending" } },
      { id: "timeout", label: { ko: "Timeout Resume", en: "Timeout Resume" }, x: 330, y: -50, delay: 0.5, tooltip: { ko: "미완료 Saga 자동 재개 (1시간 이내)", en: "Incomplete Saga auto-resume (within 1hr)" } },
    ],
    edges: [
      { id: "e1", source: "db-saved", target: "gh-queued" },
      { id: "e2", source: "gh-queued", target: "ai-queued" },
      { id: "e3", source: "ai-queued", target: "done" },
      { id: "e-gh-err", source: "gh-queued", target: "token-invalid" },
      { id: "e-tk-done", source: "token-invalid", target: "done" },
      { id: "e-ai-skip", source: "ai-queued", target: "ai-skipped" },
      { id: "e-sk-done", source: "ai-skipped", target: "done" },
      { id: "e-ai-err", source: "ai-queued", target: "delayed" },
      { id: "e-dl-done", source: "delayed", target: "done" },
      { id: "e-timeout", source: "timeout", target: "gh-queued" },
    ],
  },

  monitoring: {
    nodes: [
      { id: "ms", label: { ko: "6 Microservices", en: "6 Microservices" }, x: 0, y: 120, delay: 0, tooltip: { ko: "NestJS 4 + FastAPI 1 + Node.js 1", en: "NestJS 4 + FastAPI 1 + Node.js 1" } },
      { id: "prometheus", label: { ko: "Prometheus", en: "Prometheus" }, x: 280, y: 40, delay: 0.1, tooltip: { ko: "메트릭 수집 — 30초 스크랩 주기", en: "Metrics collection — 30s scrape interval" } },
      { id: "loki", label: { ko: "Loki", en: "Loki" }, x: 280, y: 200, delay: 0.1, tooltip: { ko: "로그 집계 — 구조화된 로그 쿼리", en: "Log aggregation — structured log queries" } },
      { id: "grafana", label: { ko: "Grafana", en: "Grafana" }, x: 560, y: 120, delay: 0.2, tooltip: { ko: "대시보드 + Alertmanager 알림", en: "Dashboards + Alertmanager alerts" } },
    ],
    edges: [
      { id: "e1", source: "ms", target: "prometheus" },
      { id: "e2", source: "ms", target: "loki" },
      { id: "e3", source: "prometheus", target: "grafana" },
      { id: "e4", source: "loki", target: "grafana" },
    ],
  },

  cicd: {
    nodes: [
      { id: "secret-scan", label: { ko: "Secret Scan", en: "Secret Scan" }, x: 0, y: 0, delay: 0, tooltip: { ko: "gitleaks — 시크릿 유출 탐지", en: "gitleaks — secret leak detection" } },
      { id: "detect-changes", label: { ko: "Path Filter", en: "Path Filter" }, x: 0, y: 100, delay: 0, tooltip: { ko: "dorny/paths-filter — 모노레포 변경 감지", en: "dorny/paths-filter — monorepo change detection" } },
      { id: "commit-lint", label: { ko: "Commit Lint", en: "Commit Lint" }, x: 0, y: 200, delay: 0, tooltip: { ko: "Conventional Commits 규칙 검증", en: "Conventional Commits rule validation" } },
      { id: "quality-nestjs", label: { ko: "ESLint+TS (×5)", en: "ESLint+TS (×5)" }, x: 200, y: 0, delay: 0.12, tooltip: { ko: "NestJS 5개 서비스 린트 + 타입 체크", en: "NestJS 5 services lint + type check" } },
      { id: "quality-python", label: { ko: "ruff (AI)", en: "ruff (AI)" }, x: 200, y: 100, delay: 0.12, tooltip: { ko: "FastAPI AI 서비스 Python 린트", en: "FastAPI AI service Python lint" } },
      { id: "quality-frontend", label: { ko: "next lint+TS", en: "next lint+TS" }, x: 200, y: 200, delay: 0.12, tooltip: { ko: "Next.js 프론트엔드 린트 + 타입 체크", en: "Next.js frontend lint + type check" } },
      { id: "test-node", label: { ko: "Jest (×5)", en: "Jest (×5)" }, x: 400, y: 0, delay: 0.24, tooltip: { ko: "NestJS 서비스별 단위/통합 테스트", en: "NestJS per-service unit/integration tests" } },
      { id: "test-ai", label: { ko: "pytest", en: "pytest" }, x: 400, y: 100, delay: 0.24, tooltip: { ko: "AI 분석 파이프라인 테스트", en: "AI analysis pipeline tests" } },
      { id: "test-frontend", label: { ko: "Jest (FE)", en: "Jest (FE)" }, x: 400, y: 200, delay: 0.24, tooltip: { ko: "React 컴포넌트 테스트", en: "React component tests" } },
      { id: "build-services", label: { ko: "Docker ARM64 (×6)", en: "Docker ARM64 (×6)" }, x: 600, y: 40, delay: 0.36, tooltip: { ko: "QEMU 크로스컴파일 + GHA 캐시", en: "QEMU cross-compile + GHA cache" } },
      { id: "build-frontend", label: { ko: "Next.js ARM64", en: "Next.js ARM64" }, x: 600, y: 160, delay: 0.36, tooltip: { ko: "프론트엔드 ARM64 이미지 빌드", en: "Frontend ARM64 image build" } },
      { id: "trivy", label: { ko: "Trivy Scan (×7)", en: "Trivy Scan (×7)" }, x: 600, y: 280, delay: 0.48, tooltip: { ko: "CRITICAL/HIGH 취약점 스캔 + SARIF 업로드", en: "CRITICAL/HIGH vuln scan + SARIF upload" } },
      { id: "deploy", label: { ko: "ArgoCD Deploy", en: "ArgoCD Deploy" }, x: 400, y: 320, delay: 0.6, tooltip: { ko: "GitOps 자동 배포 — 이미지 태그 업데이트", en: "GitOps auto deploy — image tag update" } },
    ],
    edges: [
      { id: "e-dc-qn", source: "detect-changes", target: "quality-nestjs" },
      { id: "e-dc-qp", source: "detect-changes", target: "quality-python" },
      { id: "e-dc-qf", source: "detect-changes", target: "quality-frontend" },
      { id: "e-qn-tn", source: "quality-nestjs", target: "test-node" },
      { id: "e-qp-ta", source: "quality-python", target: "test-ai" },
      { id: "e-qf-tf", source: "quality-frontend", target: "test-frontend" },
      { id: "e-tn-bs", source: "test-node", target: "build-services" },
      { id: "e-ta-bs", source: "test-ai", target: "build-services" },
      { id: "e-tf-bf", source: "test-frontend", target: "build-frontend" },
      { id: "e-bs-tr", source: "build-services", target: "trivy" },
      { id: "e-bf-tr", source: "build-frontend", target: "trivy" },
      { id: "e-tr-dp", source: "trivy", target: "deploy" },
      { id: "e-ss-dp", source: "secret-scan", target: "deploy" },
    ],
  },
};
